name: git-invader

on:
    schedule:
        - cron: "0 */3 * * *"
    workflow_dispatch:
    push:
        branches: [main, master]

jobs:
    generate:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Generate SVG
              uses: VARDHAMANPATEL23/git-invader@v1.2.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  github_username: ${{ github.repository_owner }}
                  output_dir: dist
                  color: multi
                  mode: dark

            - name: Push to output branch
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: output
                  build_dir: dist
                  keep_history: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
